name: TorchBench PR Test on A10G
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  CONDA_ENV: "torchbench"
  DOCKER_IMAGE: "ghcr.io/pytorch/torchbench:latest"

jobs:
  pr-test:
    # AWS A10G GPU instance label: linux.g5.4xlarge.nvidia.gpu
    # OS version: Amazon Linux 2
    runs-on: [self-hosted, linux.g5.4xlarge.nvidia.gpu]
    timeout-minutes: 1440 # 24 hours
    steps:
      - name: Checkout TorchBench
        uses: actions/checkout@v3
        with:
          path: benchmark
      - name: Pull docker image
        uses: pytorch/test-infra/.github/actions/pull-docker-image@main
        with:
          docker-image: ${{ env.DOCKER_IMAGE }}
      - name: Install Conda and basic packages
        run: |
          bash scripts/install_basics_amzn_linux_2.sh
      - name: Install NVIDIA Driver, docker runtime, set GPU_FLAG
        id: install-nvidia-driver
        uses: pytorch/test-infra/.github/actions/setup-nvidia@main
      - name: Install and Test TorchBench
        run: |
          container_name=$(docker run \
            -e CONDA_ENV \
            --tty \
            --detach \
            -v "${PWD}/benchmark:/benchmark" \
            -w /workspace \
            "${{ env.DOCKER_IMAGE }}"
          )

          docker exec -t -w "/benchmark" "${container_name}" bash -c \
            ". ${HOME}/miniconda3/etc/profile.d/conda.sh && conda activate ${CONDA_ENV} && cd /benchmark && python install.py"

          docker exec -t -w "/benchmark" "${container_name}" bash -c \
            ". ${HOME}/miniconda3/etc/profile.d/conda.sh && conda activate ${CONDA_ENV} " \
            " && cd /benchmark && python -m components.test.test_subprocess" \
            "python -m components.test.test_worker"

          docker exec -t -w "/benchmark" "${container_name}" bash -c \
            ". ${HOME}/miniconda3/etc/profile.d/conda.sh && conda activate ${CONDA_ENV} " \
            " && cd /benchmark && python test.py"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}-${{ github.event_name == 'workflow_dispatch' }}
  cancel-in-progress: true
